### PR TITLE
Feat/server docs and feat/update-sbc-version

### PR DESCRIPTION
**Pull request by bmikkelsen22**
This has the changes from feat/update-sbc-version because dev is so out of date. Lets fix that :)

### CODE REVIEW

**Comment by danvanhorn** [comment]
Will you please fix the Jump to Filter link? It needs to have the AdvancedFilter Id passed into it as a prop.

**Comment by danvanhorn** [comment]
Can you investigate the pdf generation and see if this is a code issue?

**Comment by bmikkelsen22** [comment]
It's working on my computer. Maybe pull the changes I made?

**Comment by danvanhorn** [comment]
This is looking good but we may want to look at this.
image

**Review by tnoelcke — APPROVED** [review]
Looks good! This is what we are currently working from so we should probably have gotten it merged quite a while ago.

**Pull request merged**
